- hosts: 127.0.0.1
  name: Local Testing no Roles
  become: yes

  tasks:
    - name: test task
      block:
        - name: test message
          shell: echo "supy supy!" >> /testlog.txt
          notify: update SNOW with success
        - debug:
            msg: "task1 is a success!"
        - name: update SNOW with success
          uri:
            url: http://httpbin.org/get
            method: GET
            status_code: 299
      rescue:
        - name: error handle
          shell: echo "fail saucers" >> /testlog.txt

  handlers:
    - name: update SNOW with success
      uri:
        url: http://httpbin.org/get
        method: GET
        status_code: 200
