---
- hosts: 127.0.0.1
  name: Local Testing no Roles
  become: yes

  tasks:
    - name: test task
      block:
        - name: Greet World
          shell: echo "sup home doggies!"
          notify: update SNOW with success
        - debug:
          msg: "This is a fail!"
      rescue:
        - name: error handle
          shell: echo "fail saucers :( "

  handlers:
    - name: update SNOW with success
      uri:
        url: "http://google.com"
        method: GET
        status_code: 201
